
## Woodchucks seed info ##

User.create(first_name: "Adrian", last_name: "Soghoian", email: "adriansoghoian@gmail.com", password: "test", password_confirmation: "test")
User.create(first_name: "Alexis", last_name: "Ernst", email: "ldernst@umich.edu", password: "test", password_confirmation: "test")
User.create(first_name: "Armen", last_name: "Vartan", email: "vartan.armen@gmail.com", password: "test", password_confirmation: "test")
User.create(first_name: "Ben", last_name: "Brostoff", email: "ben.brostoff@gmail.com", password: "test", password_confirmation: "test")
User.create(first_name: "Brendan", last_name: "Susens-Jackson", email: "bsusensjackson@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Christian", last_name: "Moon", email: "cmoon.nyc@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Gregory", last_name: "Knudsen", email: "greg.knudsen09@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Gregory", last_name: "Piccolo", email: "greg.piccolo@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Ian", last_name: "Shuff", email: "ianvshuff@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Jake", last_name: "Wayne", email: "jhwayne@umich.edu" , password: "test", password_confirmation: "test")
User.create(first_name: "John", last_name: "Quigley", email: "johnpeterquigley@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Joseph", last_name: "Cohen", email: "jdcohen9@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Kai", last_name: "Prout", email: "kaiprt@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Katie", last_name: "Reiner", email: "kreiner@umich.edu", password: "test", password_confirmation: "test")
User.create(first_name: "Ken", last_name: "Mendonca", email: "mendoca.kr@gmail.com", password: "test", password_confirmation: "test")
User.create(first_name: "Matthieu", last_name: "Gavaudan", email: "mlg2199@columbia.edu" , password: "test", password_confirmation: "test")
User.create(first_name: "Drew", last_name: "Teter", email: "mteter13@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Natalie", last_name: "Baer", email: "ncbaer@gmail.com", password: "test", password_confirmation: "test")
User.create(first_name: "Richard", last_name: "Macias", email: "rjny86@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Siddharth", last_name: "Patel", email: "sidpatel13@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Stella", last_name: "Kim", email: "stellajkimm@gmail.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Victor", last_name: "Schaeperkoetter", email: "victor.schaeperkoetter@yahoo.com" , password: "test", password_confirmation: "test")
User.create(first_name: "Antonio", last_name: "Perez", email: "rantoniops@gmail.com" , password: "test", password_confirmation: "test")
